#!/bin/bash
# PreToolUse(Bash): keeps commit messages and PR metadata project-only.
INPUT=$(cat)
PY="$(command -v python3 || command -v python)"
if [ -z "$PY" ]; then
  echo "Невозможно проверить публичные Git-метаданные: Python 3.9+ не найден." >&2
  exit 2
fi
# Parse the hook JSON properly instead of grepping a "command" field regex, so an embedded/escaped
# quote inside a multi-line commit message never truncates matching — and so this only inspects
# the actual command text, not unrelated payload fields (cwd, transcript_path, session_id, ...),
# which always contain this repo's own name ("claude-agent-harness") and would otherwise
# self-trigger FORBIDDEN on every single invocation regardless of the command being run.
COMMAND="$(printf '%s' "$INPUT" | "$PY" -c '
import json, sys
try:
    data = json.load(sys.stdin)
    command = data["tool_input"]["command"]
except (json.JSONDecodeError, KeyError, TypeError):
    sys.exit(1)
if not isinstance(command, str):
    sys.exit(1)
sys.stdout.write(command)
')"
if [ $? -ne 0 ]; then
  echo "Невозможно проверить публичные Git-метаданные: hook payload не содержит tool_input.command." >&2
  exit 2
fi

FORBIDDEN='\bclaude\b|\bopenai\b|\bchatgpt\b|\bgpt[-_ ]?[0-9]|\bcopilot\b|\bgemini\b|\bcodex\b|\bco-authored[- ]by\b|\bai[-_ ]?(agent|assistant|generated)\b'
# Two tiers. Commit messages and PR/MR titles and bodies are checked against FORBIDDEN. Issue
# titles and bodies and every comment or note are checked only against TRACKER_ATTRIBUTION:
# ticket text names runtimes and paths such as .claude/ as project vocabulary, so only
# attribution is blocked there — Co-Authored-By, "generated/written by <assistant>", AI-generated
# marks and assistant session URLs. A Python regex: lookarounds instead of \b, because "_" is a
# word character and \b misses a Markdown-italic trailer such as _Generated by ..._.
TRACKER_ATTRIBUTION='(?<![a-z0-9])co-authored[- ]by(?![a-z0-9])|(?<![a-z0-9])(generated|written|created|authored|produced)\s+(with|by|using|via)\s+\[?(claude|chatgpt|openai|copilot|gemini|codex|gpt[-_ ]?[0-9])|(?<![a-z0-9])ai[-_ ]?generated(?![a-z0-9])|(?<![a-z0-9.-])(claude\.ai|chatgpt\.com|chat\.openai\.com)/'

printf '%s\n' "$COMMAND" | grep -qiE 'git[[:space:]]+(commit|push)|(gh|glab)[[:space:]]+(pr|mr|issue)[[:space:]]+(create|new|edit|update|comment|note)' || exit 0

# Heredoc bodies are stdin data, not shell words: they are cut out before publish commands are
# detected and tokenized, so a script that only mentions `git commit` publishes nothing. A body
# is checked only through the argument that holds its operator, as in -m "$(cat <<'EOF' ...)".
# Prints 1 when the command pushes or creates/edits a PR/MR, so unpushed messages need a check.
check_command_metadata() {
  printf '%s' "$COMMAND" | FORBIDDEN="$FORBIDDEN" TRACKER_ATTRIBUTION="$TRACKER_ATTRIBUTION" "$PY" -c '
import os
import re
import shlex
import sys


def fail(message):
    print(message, file=sys.stderr)
    raise SystemExit(2)


QUOTE = "\x27"
METACHARACTERS = " \t\n|&;()<>"
MARKER = re.compile("\0([0-9]+)\0")


def read_word(text, index):
    word = []
    while index < len(text) and text[index] not in METACHARACTERS:
        char = text[index]
        if char in (QUOTE, "\""):
            end = text.find(char, index + 1)
            if end < 0:
                return "", index
            word.append(text[index + 1 : end])
            index = end + 1
        elif char == "\\":
            word.append(text[index + 1 : index + 2])
            index += 2
        else:
            word.append(char)
            index += 1
    return "".join(word), index


def read_body(text, index, delimiter, strip_tabs):
    lines = []
    while index < len(text):
        end = text.find("\n", index)
        end = len(text) if end < 0 else end
        line = text[index:end]
        index = end + 1
        if (line.lstrip("\t") if strip_tabs else line) == delimiter:
            break
        lines.append(line)
    return "\n".join(lines), index


def cut_heredocs(text):
    """Replace each heredoc operator with a marker and cut its body out of the shell text."""
    shell, bodies, pending, stack = [], [], [], []
    index = 0
    while index < len(text):
        char = text[index]
        top = stack[-1] if stack else ""
        step = 1
        if top == QUOTE:
            if char == QUOTE:
                stack.pop()
        elif char == "\\":
            step = 2
        elif top == "((":
            if text.startswith("))", index):
                stack.pop()
                step = 2
        elif text.startswith("$((", index):
            stack.append("((")
            step = 3
        elif text.startswith("$(", index):
            stack.append("(")
            step = 2
        elif char == "`":
            if top == "`":
                stack.pop()
            else:
                stack.append(char)
        elif top == "\"":
            if char == "\"":
                stack.pop()
        elif char in (QUOTE, "\""):
            stack.append(char)
        elif char == "#" and (index == 0 or text[index - 1] in " \t\n;&|()"):
            end = text.find("\n", index)
            step = (len(text) if end < 0 else end) - index
        elif text.startswith("((", index):
            stack.append("((")
            step = 2
        elif char == "(":
            stack.append(char)
        elif char == ")" and top == "(":
            stack.pop()
        elif text.startswith("<<<", index):
            step = 3
        elif text.startswith("<<", index):
            start = index + 2
            strip_tabs = text.startswith("-", start)
            start += strip_tabs
            while text[start : start + 1] in (" ", "\t"):
                start += 1
            delimiter, end = read_word(text, start)
            if delimiter:
                shell.append("\0%d\0" % (len(bodies) + len(pending)))
                pending.append((delimiter, strip_tabs))
                index = end
                continue
            step = 2
        elif char == "\n" and pending:
            shell.append(char)
            index += 1
            for delimiter, strip_tabs in pending:
                body, index = read_body(text, index, delimiter, strip_tabs)
                bodies.append(body)
            pending = []
            continue
        shell.append(text[index : index + step])
        index += step
    bodies.extend("" for _ in pending)
    return "".join(shell), bodies


shell, bodies = cut_heredocs(sys.stdin.read())
is_commit = re.search(r"git\s+commit", shell, re.IGNORECASE)
is_pr = re.search(r"(gh\s+pr|glab\s+mr)\s+(create|new|edit|update)", shell, re.IGNORECASE)
is_push = re.search(r"git\s+push", shell, re.IGNORECASE)
is_tracker = re.search(r"(gh|glab)\s+(issue|pr|mr)\s+(create|new|edit|update|comment|note)", shell, re.IGNORECASE)
if not (is_commit or is_pr or is_push or is_tracker):
    raise SystemExit(0)

try:
    lexer = shlex.shlex(shell, posix=True)
    lexer.whitespace_split = True
    lexer.commenters = ""
    lexer.escape = ""
    tokens = list(lexer)
except ValueError:
    fail("Невозможно проверить публичные Git-метаданные: команда содержит незакрытую кавычку.")

forbidden = re.compile(os.environ["FORBIDDEN"], re.IGNORECASE)
METADATA = (forbidden, "Публичные Git-метаданные должны содержать только сведения об изменении проекта: автоматическая атрибуция, имена моделей и session URL запрещены.")
TRACKER = (
    re.compile(os.environ["TRACKER_ATTRIBUTION"], re.IGNORECASE),
    "Публичный текст трекера не должен содержать автоматическую атрибуцию: trailer Co-Authored-By, отметку generated/written by, пометку AI-generated и ссылки на сессии ассистента.",
)


def has_sequence(*parts):
    return any(tokens[index : index + len(parts)] == list(parts) for index in range(len(tokens)))


def values(options):
    result = []
    index = 0
    while index < len(tokens):
        token = tokens[index]
        if token in options:
            if index + 1 >= len(tokens):
                fail("Невозможно проверить публичные Git-метаданные: у параметра сообщения нет значения.")
            result.append(tokens[index + 1])
            index += 2
            continue
        for option in options:
            if option.startswith("--") and token.startswith(option + "="):
                result.append(token[len(option) + 1 :])
                break
        else:
            index += 1
            continue
        index += 1
    return result


def check_text(text, tier=METADATA):
    pattern, message = tier
    text = MARKER.sub(lambda match: bodies[int(match.group(1))], text)
    if pattern.search(text):
        fail(message)


def check_files(paths, tier=METADATA):
    for path in paths:
        if not os.path.isfile(path):
            fail("Невозможно проверить публичные Git-метаданные: файл сообщения должен быть доступен по literal-пути.")
        try:
            with open(path, encoding="utf-8") as source:
                check_text(source.read(), tier)
        except OSError:
            fail("Невозможно прочитать файл публичных Git-метаданных.")


if has_sequence("git", "commit"):
    check_texts = values({"-m", "--message", "--trailer"})
    check_files(values({"-F", "--file"}))
    for text in check_texts:
        check_text(text)

if (has_sequence("gh", "pr", "create") or has_sequence("gh", "pr", "edit") or
        has_sequence("glab", "mr", "create") or has_sequence("glab", "mr", "edit")):
    check_files(values({"--body-file", "--description-file"}))
    for text in values({"--title", "--body", "--description"}):
        check_text(text)

# A short flag means what its own CLI says: gh -d is --draft, glab -b is --target-branch and -m
# is --milestone outside notes, so each publication command reads only the flags that carry text
# in it. PR/MR metadata uses the METADATA tier; issue text, comments and notes use TRACKER.
GH = ({"t": "text", "b": "text"}, {"--title": "text", "--body": "text"})
GLAB = ({"t": "text", "d": "text"}, {"--title": "text", "--description": "text"})
NOTE = ({"m": "text"}, {"--message": "text"})
PUBLICATIONS = (
    ("gh pr create|new|edit", METADATA, GH),
    ("glab mr create|new|edit|update", METADATA, GLAB),
    ("gh issue create|new|edit|comment", TRACKER, GH),
    ("gh pr comment", TRACKER, GH),
    ("glab issue create|new|update", TRACKER, GLAB),
    ("glab issue note", TRACKER, NOTE),
    ("glab mr note", TRACKER, NOTE),
)


def flag_values(args, shorts, longs):
    """Return (kind, value) for each text flag in args, in every reading the CLI may take.

    A short flag outside the table counts as a boolean, and a flag value is read again as a
    flag, so a value-taking flag the table omits cannot hide the text flag that follows it.
    """
    found, taken = [], False
    for index, token in enumerate(args):
        kind = value = None
        if token.startswith("--"):
            name, equals, rest = token.partition("=")
            kind = longs.get(name)
            value = rest if equals else None
        elif token.startswith("-"):
            for offset, flag in enumerate(token[1:], 2):
                kind = shorts.get(flag)
                if kind:
                    rest = token[offset:]
                    value = (rest[1:] if rest.startswith("=") else rest) or None
                    break
        consumed, taken = taken, False
        if kind is None:
            continue
        if value is None:
            if index + 1 == len(args):
                if consumed:
                    continue
                fail("Невозможно проверить публичные Git-метаданные: у параметра сообщения нет значения.")
            value, taken = args[index + 1], True
        found.append((kind, value))
    return found


programs = [re.split(r"[\\/]", token)[-1] for token in tokens]
for spec, tier, (shorts, longs) in PUBLICATIONS:
    *command, verbs = spec.split()
    for verb in verbs.split("|"):
        key = [*command, verb]
        for index in range(len(tokens)):
            if programs[index] == key[0] and tokens[index + 1 : index + len(key)] == key[1:]:
                for kind, value in flag_values(tokens[index + len(key) :], shorts, longs):
                    if kind == "text":
                        check_text(value, tier)

if is_push or is_pr:
    print(1)
'
}

PUBLISHES="$(check_command_metadata)" || exit 2

if [ "$PUBLISHES" = 1 ]; then
  LOCAL_MESSAGES="$(git -C "${CLAUDE_PROJECT_DIR:-.}" log --format=%B --no-merges HEAD --not --remotes 2>/dev/null)"
  if printf '%s\n' "$LOCAL_MESSAGES" | grep -qiE "$FORBIDDEN"; then
    echo "Публикация заблокирована: непереданный commit message содержит запрещённую автоматическую атрибуцию или ссылку на сессию." >&2
    exit 2
  fi
fi

exit 0
