#!/usr/bin/env python3
"""Build the compact on-demand skill registry from canonical SKILL.md files."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
OUTPUT = SKILLS / "REGISTRY.md"


def metadata(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise SystemExit(f"missing frontmatter: {path}")
    frontmatter = text.split("---", 2)[1]
    name = re.search(r"^name:\s*(.+?)\s*$", frontmatter, re.MULTILINE)
    description = re.search(r"^description:\s*(.+?)\s*$", frontmatter, re.MULTILINE)
    if not name or not description:
        raise SystemExit(f"missing name or description: {path}")
    return name.group(1).strip(" '\""), description.group(1).strip(" '\"")


rows: list[tuple[str, str, str]] = []
for skill_file in sorted(SKILLS.rglob("SKILL.md")):
    name, description = metadata(skill_file)
    relative = skill_file.parent.relative_to(ROOT).as_posix()
    rows.append((name, relative, description.replace("|", "\\|")))

by_name: dict[str, list[str]] = {}
for name, path, _ in rows:
    by_name.setdefault(name, []).append(path)

# A name may legitimately appear twice: once under skills/vendor/ (the pinned
# upstream original) and once under skills/first-party/ (a capability's
# override of it, selected instead of the vendor one - see CAPABILITIES.json
# `overrides`). Anything beyond that one vendor + one first-party pairing is a
# real naming collision.
bad = []
for name, paths in by_name.items():
    layers = [p.split("/")[1] for p in paths]  # paths look like "skills/<layer>/..."
    if len(paths) > 2 or len(set(layers)) != len(layers):
        bad.append(name)
if bad:
    raise SystemExit(f"duplicate skill names: {', '.join(sorted(bad))}")

lines = [
    "# Skill Registry",
    "",
    "Generated by `scripts/build-registry`. Search this file on demand; do not load the full",
    "catalog into every session.",
    "",
    "| Skill | Canonical path | When to use |",
    "|---|---|---|",
]
lines.extend(f"| `{name}` | `{path}` | {description} |" for name, path, description in rows)
OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
print(f"wrote {OUTPUT} with {len(rows)} skills")
